### ISSUE TITLE
settings saving behaviour 

### ISSUE THREAD

**Issue by emphasize** [MycroftAI/skill-reminder#37]
The skill should [save](https://github.com/MycroftAI/skill-reminder/blob/b8dc13ec00bb0feb361deb58fd71080e98ed1325/__init__.py#L218) its reminder lists to the .config/xx/xx/xx/settings.json. While this is true for the first time after every (re)boot, the second entry is only stored in some type of cache, never make its way to settings.json. While this isn't recognized if you never reboot, the list entries will be lost if you do.

[save_settings](https://github.com/MycroftAI/mycroft-core/blob/a5b7f55ae400da9d20e703ec6c8e5008be6853bd/mycroft/skills/settings.py#L93) reports "Skill settings successfully saved to ..." for the first time then stays silent after that

outputs from [checking reminder state](https://github.com/MycroftAI/skill-reminder/blob/b8dc13ec00bb0feb361deb58fd71080e98ed1325/__init__.py#L92)
Checking ('tennis morgen 18 uhr', '20200908-180000-+0200') (settings.json)
Checking ('tennis morgen 18 uhr', '20200908-180000-+0200') (cache)
Checking ('fußball morgen 13 uhr', '20200908-130000-+0200')  (cache)

settings.json
{"__mycroft_skill_firstrun": false, "reminders": [["tennis morgen 18 uhr", "20200908-180000-+0200"]]}

If you reboot the first reminder you set after that is appended to the (settings.json) list -> then only cached

**Comment by forslund** [comment]
Good find! This should be handled automatically by core but it seems it doesn't. I think I see the issue and will create a PR.

**Comment by emphasize** [comment]
Did it. thanks

**Comment by emphasize** [comment]
But i have to report a followup problem. Processing with deepcopy, failed responses (Speech recognition could not understand audio) result in the exception
`AttributeError: 'dict' object has no attribute deepcopy`

**Comment by forslund** [comment]
Do you get any more logs than that?

**Comment by forslund** [comment]
Ah when `get_response()` is used, yeah I can see the error there...

**Comment by forslund** [comment]
Thanks for noticing that, I did a replace too much in the commit. I've amended the commit now.

**Comment by krisgesling** [comment]
Fix looks good and each new reminder is now being saved to the settings. This is now available on the dev branch, or can wait for mycroft-core v20.2.5 which will be released this week or next.
