### ISSUE TITLE
specify a date/time does not work

### ISSUE THREAD

**Issue by Simulant87** [MycroftAI/skill-reminder#42]
It is not clear to me in what format I have to specify the time for a reminder.

I get the confirmation "right-o. do you want me to remind you at a specific time?" and fail with any format.
Listing my reminders afterwards, always returns I have no remindes.

I tried with and without a leading "remind me" in the response. As I am in a dialog I think I don't have to call the wake word "hey Mycroft" again:
in 15 minutes.
today in 15 minutes.
tomorrow at 9am.
at the 1. of April.
at quarter past 10pm.
at 21 and 15 minutes (trying 24hours time format).

nothing works. Please help me how can I set a correct time?
Does it have something to do with my default/device configured date time format? I am using 24 hours format.

**Comment by forslund** [comment]
Tested it here, and it seems like the dialog entry is broken.

If I say "hey mycroft remind me to be awesome at 9am tomorrow" it works but if I use the dialog flow it doesn't work just as you describe.
